import { test, expect } from "bun:test"
import circuitJson from "./circuit-json-pack-conversion01.json"
import { convertCircuitJsonToPackOutput } from "../../lib/testing/convertCircuitJsonToPackOutput"
import { getSvgFromGraphicsObject } from "graphics-debug"
import { getGraphicsFromPackOutput } from "../../lib/testing/getGraphicsFromPackOutput"
import type { CircuitJson } from "circuit-json"
import { runTscircuitCode } from "tscircuit"

test("circuit-json-pack-conversion02", async () => {
  const circuitJson = await runTscircuitCode(`
    export default () => (
        <board routingDisabled>
          <group name="G1">
            <group name="G2">
              <resistor name="R1" resistance="1k" footprint="0402" />
              <capacitor name="C1" capacitance="100nF" footprint="0402" />
            </group>
            <resistor name="R2" resistance="2k" footprint="0603" />
          </group>
          <resistor name="R3" resistance="3k" footprint="0805" />
        </board>
      )
  `)
  expect(circuitJson).toMatchInlineSnapshot(`
    [
      {
        "software_used_string": "@tscircuit/core@0.0.586",
        "source_project_metadata_id": "source_project_metadata_0",
        "type": "source_project_metadata",
      },
      {
        "is_subcircuit": undefined,
        "name": "G2",
        "parent_source_group_id": "source_group_1",
        "source_group_id": "source_group_0",
        "type": "source_group",
      },
      {
        "is_subcircuit": undefined,
        "name": "G1",
        "parent_source_group_id": "source_group_2",
        "source_group_id": "source_group_1",
        "type": "source_group",
      },
      {
        "is_subcircuit": true,
        "name": undefined,
        "source_group_id": "source_group_2",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "source_group",
      },
      {
        "name": "pin1",
        "pin_number": 1,
        "port_hints": [
          "anode",
          "pos",
          "left",
          "pin1",
          "1",
        ],
        "source_component_id": "source_component_0",
        "source_port_id": "source_port_0",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "source_port",
      },
      {
        "name": "pin2",
        "pin_number": 2,
        "port_hints": [
          "cathode",
          "neg",
          "right",
          "pin2",
          "2",
        ],
        "source_component_id": "source_component_0",
        "source_port_id": "source_port_1",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "source_port",
      },
      {
        "are_pins_interchangeable": true,
        "display_resistance": "1kΩ",
        "ftype": "simple_resistor",
        "manufacturer_part_number": undefined,
        "name": "R1",
        "resistance": 1000,
        "source_component_id": "source_component_0",
        "source_group_id": "source_group_0",
        "supplier_part_numbers": {
          "jlcpcb": [
            "C2906901",
            "C185446",
            "C25086",
          ],
        },
        "type": "source_component",
      },
      {
        "name": "pin1",
        "pin_number": 1,
        "port_hints": [
          "pos",
          "pin1",
          "1",
        ],
        "source_component_id": "source_component_1",
        "source_port_id": "source_port_2",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "source_port",
      },
      {
        "name": "pin2",
        "pin_number": 2,
        "port_hints": [
          "neg",
          "pin2",
          "2",
        ],
        "source_component_id": "source_component_1",
        "source_port_id": "source_port_3",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "source_port",
      },
      {
        "are_pins_interchangeable": true,
        "capacitance": 0.0000001,
        "display_capacitance": "100nF",
        "ftype": "simple_capacitor",
        "manufacturer_part_number": undefined,
        "max_decoupling_trace_length": undefined,
        "max_voltage_rating": undefined,
        "name": "C1",
        "source_component_id": "source_component_1",
        "source_group_id": "source_group_0",
        "supplier_part_numbers": {
          "jlcpcb": [
            "C1525",
            "C6119799",
            "C307331",
          ],
        },
        "type": "source_component",
      },
      {
        "name": "pin1",
        "pin_number": 1,
        "port_hints": [
          "anode",
          "pos",
          "left",
          "pin1",
          "1",
        ],
        "source_component_id": "source_component_2",
        "source_port_id": "source_port_4",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "source_port",
      },
      {
        "name": "pin2",
        "pin_number": 2,
        "port_hints": [
          "cathode",
          "neg",
          "right",
          "pin2",
          "2",
        ],
        "source_component_id": "source_component_2",
        "source_port_id": "source_port_5",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "source_port",
      },
      {
        "are_pins_interchangeable": true,
        "display_resistance": "2kΩ",
        "ftype": "simple_resistor",
        "manufacturer_part_number": undefined,
        "name": "R2",
        "resistance": 2000,
        "source_component_id": "source_component_2",
        "source_group_id": "source_group_1",
        "supplier_part_numbers": {
          "jlcpcb": [
            "C2907139",
            "C22977",
            "C2933191",
          ],
        },
        "type": "source_component",
      },
      {
        "name": "pin1",
        "pin_number": 1,
        "port_hints": [
          "anode",
          "pos",
          "left",
          "pin1",
          "1",
        ],
        "source_component_id": "source_component_3",
        "source_port_id": "source_port_6",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "source_port",
      },
      {
        "name": "pin2",
        "pin_number": 2,
        "port_hints": [
          "cathode",
          "neg",
          "right",
          "pin2",
          "2",
        ],
        "source_component_id": "source_component_3",
        "source_port_id": "source_port_7",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "source_port",
      },
      {
        "are_pins_interchangeable": true,
        "display_resistance": "3kΩ",
        "ftype": "simple_resistor",
        "manufacturer_part_number": undefined,
        "name": "R3",
        "resistance": 3000,
        "source_component_id": "source_component_3",
        "source_group_id": "source_group_2",
        "supplier_part_numbers": {
          "jlcpcb": [
            "C17660",
            "C2930286",
            "C2933430",
          ],
        },
        "type": "source_component",
      },
      {
        "center": {
          "x": 0,
          "y": 0,
        },
        "schematic_component_id": "schematic_component_0",
        "schematic_group_id": "schematic_group_0",
        "size": {
          "height": 0.388910699999999,
          "width": 1.0583332999999997,
        },
        "source_component_id": "source_component_0",
        "symbol_display_value": "1kΩ",
        "symbol_name": "boxresistor_right",
        "type": "schematic_component",
      },
      {
        "center": {
          "x": 1.2,
          "y": 0,
        },
        "schematic_component_id": "schematic_component_1",
        "schematic_group_id": "schematic_group_0",
        "size": {
          "height": 0.8400173000000031,
          "width": 1.0583333000000001,
        },
        "source_component_id": "source_component_1",
        "symbol_display_value": "100nF",
        "symbol_name": "capacitor_right",
        "type": "schematic_component",
      },
      {
        "center": {
          "x": 0,
          "y": 0,
        },
        "height": 0,
        "is_subcircuit": undefined,
        "name": "G2",
        "schematic_component_ids": [],
        "schematic_group_id": "schematic_group_0",
        "source_group_id": "source_group_0",
        "subcircuit_id": null,
        "type": "schematic_group",
        "width": 0,
      },
      {
        "center": {
          "x": 0,
          "y": 0,
        },
        "schematic_component_id": "schematic_component_2",
        "schematic_group_id": "schematic_group_1",
        "size": {
          "height": 0.388910699999999,
          "width": 1.0583332999999997,
        },
        "source_component_id": "source_component_2",
        "symbol_display_value": "2kΩ",
        "symbol_name": "boxresistor_right",
        "type": "schematic_component",
      },
      {
        "center": {
          "x": 0,
          "y": 0,
        },
        "height": 0,
        "is_subcircuit": undefined,
        "name": "G1",
        "schematic_component_ids": [],
        "schematic_group_id": "schematic_group_1",
        "source_group_id": "source_group_1",
        "subcircuit_id": null,
        "type": "schematic_group",
        "width": 0,
      },
      {
        "center": {
          "x": 0,
          "y": 0,
        },
        "schematic_component_id": "schematic_component_3",
        "schematic_group_id": "schematic_group_2",
        "size": {
          "height": 0.388910699999999,
          "width": 1.0583332999999997,
        },
        "source_component_id": "source_component_3",
        "symbol_display_value": "3kΩ",
        "symbol_name": "boxresistor_right",
        "type": "schematic_component",
      },
      {
        "center": {
          "x": 0,
          "y": 0,
        },
        "height": 0,
        "is_subcircuit": true,
        "name": "UNNAMED_subcircuit_source_group_2",
        "schematic_component_ids": [],
        "schematic_group_id": "schematic_group_2",
        "source_group_id": "source_group_2",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "schematic_group",
        "width": 0,
      },
      {
        "center": {
          "x": -0.5512907000000002,
          "y": 0.0002732499999993365,
        },
        "display_pin_label": "pos",
        "distance_from_component_edge": 0.4,
        "facing_direction": "left",
        "is_connected": false,
        "pin_number": 1,
        "schematic_component_id": "schematic_component_0",
        "schematic_port_id": "schematic_port_0",
        "side_of_component": undefined,
        "source_port_id": "source_port_0",
        "true_ccw_index": undefined,
        "type": "schematic_port",
      },
      {
        "center": {
          "x": 0.5512907000000002,
          "y": -0.0002732499999993365,
        },
        "display_pin_label": "neg",
        "distance_from_component_edge": 0.4,
        "facing_direction": "right",
        "is_connected": false,
        "pin_number": 2,
        "schematic_component_id": "schematic_component_0",
        "schematic_port_id": "schematic_port_1",
        "side_of_component": undefined,
        "source_port_id": "source_port_1",
        "true_ccw_index": undefined,
        "type": "schematic_port",
      },
      {
        "center": {
          "x": 0.6487906999999997,
          "y": -0.00027334999999961695,
        },
        "display_pin_label": "pos",
        "distance_from_component_edge": 0.4,
        "facing_direction": "left",
        "is_connected": false,
        "pin_number": 1,
        "schematic_component_id": "schematic_component_1",
        "schematic_port_id": "schematic_port_2",
        "side_of_component": undefined,
        "source_port_id": "source_port_2",
        "true_ccw_index": undefined,
        "type": "schematic_port",
      },
      {
        "center": {
          "x": 1.7512093000000002,
          "y": 0.00027334999999961695,
        },
        "display_pin_label": "neg",
        "distance_from_component_edge": 0.4,
        "facing_direction": "right",
        "is_connected": false,
        "pin_number": 2,
        "schematic_component_id": "schematic_component_1",
        "schematic_port_id": "schematic_port_3",
        "side_of_component": undefined,
        "source_port_id": "source_port_3",
        "true_ccw_index": undefined,
        "type": "schematic_port",
      },
      {
        "center": {
          "x": -0.5512907000000002,
          "y": 0.0002732499999993365,
        },
        "display_pin_label": "pos",
        "distance_from_component_edge": 0.4,
        "facing_direction": "left",
        "is_connected": false,
        "pin_number": 1,
        "schematic_component_id": "schematic_component_2",
        "schematic_port_id": "schematic_port_4",
        "side_of_component": undefined,
        "source_port_id": "source_port_4",
        "true_ccw_index": undefined,
        "type": "schematic_port",
      },
      {
        "center": {
          "x": 0.5512907000000002,
          "y": -0.0002732499999993365,
        },
        "display_pin_label": "neg",
        "distance_from_component_edge": 0.4,
        "facing_direction": "right",
        "is_connected": false,
        "pin_number": 2,
        "schematic_component_id": "schematic_component_2",
        "schematic_port_id": "schematic_port_5",
        "side_of_component": undefined,
        "source_port_id": "source_port_5",
        "true_ccw_index": undefined,
        "type": "schematic_port",
      },
      {
        "center": {
          "x": -0.5512907000000002,
          "y": 0.0002732499999993365,
        },
        "display_pin_label": "pos",
        "distance_from_component_edge": 0.4,
        "facing_direction": "left",
        "is_connected": false,
        "pin_number": 1,
        "schematic_component_id": "schematic_component_3",
        "schematic_port_id": "schematic_port_6",
        "side_of_component": undefined,
        "source_port_id": "source_port_6",
        "true_ccw_index": undefined,
        "type": "schematic_port",
      },
      {
        "center": {
          "x": 0.5512907000000002,
          "y": -0.0002732499999993365,
        },
        "display_pin_label": "neg",
        "distance_from_component_edge": 0.4,
        "facing_direction": "right",
        "is_connected": false,
        "pin_number": 2,
        "schematic_component_id": "schematic_component_3",
        "schematic_port_id": "schematic_port_7",
        "side_of_component": undefined,
        "source_port_id": "source_port_7",
        "true_ccw_index": undefined,
        "type": "schematic_port",
      },
      {
        "center": {
          "x": 0,
          "y": 0,
        },
        "height": 0.6,
        "layer": "top",
        "pcb_component_id": "pcb_component_0",
        "pcb_group_id": "pcb_group_0",
        "rotation": 0,
        "source_component_id": "source_component_0",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_component",
        "width": 1.6,
      },
      {
        "center": {
          "x": 0,
          "y": 0,
        },
        "height": 0.6,
        "layer": "top",
        "pcb_component_id": "pcb_component_1",
        "pcb_group_id": "pcb_group_0",
        "rotation": 0,
        "source_component_id": "source_component_1",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_component",
        "width": 1.6,
      },
      {
        "autorouter_configuration": undefined,
        "center": {
          "x": 0,
          "y": 0,
        },
        "height": 0.6,
        "is_subcircuit": undefined,
        "name": "G2",
        "pcb_component_ids": [],
        "pcb_group_id": "pcb_group_0",
        "source_group_id": "source_group_0",
        "subcircuit_id": null,
        "type": "pcb_group",
        "width": 1.6,
      },
      {
        "center": {
          "x": 0,
          "y": 0,
        },
        "height": 1,
        "layer": "top",
        "pcb_component_id": "pcb_component_2",
        "pcb_group_id": "pcb_group_1",
        "rotation": 0,
        "source_component_id": "source_component_2",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_component",
        "width": 2.8,
      },
      {
        "autorouter_configuration": undefined,
        "center": {
          "x": 0,
          "y": 0,
        },
        "height": 1,
        "is_subcircuit": undefined,
        "name": "G1",
        "pcb_component_ids": [],
        "pcb_group_id": "pcb_group_1",
        "source_group_id": "source_group_1",
        "subcircuit_id": null,
        "type": "pcb_group",
        "width": 2.8,
      },
      {
        "center": {
          "x": 0,
          "y": 0,
        },
        "height": 1.2,
        "layer": "top",
        "pcb_component_id": "pcb_component_3",
        "rotation": 0,
        "source_component_id": "source_component_3",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_component",
        "width": 3,
      },
      {
        "center": {
          "x": 0,
          "y": 0,
        },
        "height": 5.2,
        "material": "fr4",
        "num_layers": 4,
        "outline": undefined,
        "pcb_board_id": "pcb_board_0",
        "thickness": 1.4,
        "type": "pcb_board",
        "width": 7,
      },
      {
        "height": 0.6,
        "layer": "top",
        "pcb_component_id": "pcb_component_0",
        "pcb_group_id": "pcb_group_0",
        "pcb_port_id": "pcb_port_0",
        "pcb_smtpad_id": "pcb_smtpad_0",
        "port_hints": [
          "1",
          "left",
        ],
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_smtpad",
        "width": 0.6,
        "x": -0.5,
        "y": 0,
      },
      {
        "height": 0.42,
        "layer": "top",
        "pcb_component_id": "pcb_component_0",
        "pcb_group_id": "pcb_group_0",
        "pcb_smtpad_id": "pcb_smtpad_0",
        "pcb_solder_paste_id": "pcb_solder_paste_0",
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_solder_paste",
        "width": 0.42,
        "x": -0.5,
        "y": 0,
      },
      {
        "height": 0.6,
        "layer": "top",
        "pcb_component_id": "pcb_component_0",
        "pcb_group_id": "pcb_group_0",
        "pcb_port_id": "pcb_port_1",
        "pcb_smtpad_id": "pcb_smtpad_1",
        "port_hints": [
          "2",
          "right",
        ],
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_smtpad",
        "width": 0.6,
        "x": 0.5,
        "y": 0,
      },
      {
        "height": 0.42,
        "layer": "top",
        "pcb_component_id": "pcb_component_0",
        "pcb_group_id": "pcb_group_0",
        "pcb_smtpad_id": "pcb_smtpad_1",
        "pcb_solder_paste_id": "pcb_solder_paste_1",
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_solder_paste",
        "width": 0.42,
        "x": 0.5,
        "y": 0,
      },
      {
        "layer": "top",
        "pcb_component_id": "pcb_component_0",
        "pcb_group_id": "pcb_group_0",
        "pcb_silkscreen_path_id": "pcb_silkscreen_path_0",
        "route": [
          {
            "x": 0.5,
            "y": 0.7,
          },
          {
            "x": -1,
            "y": 0.7,
          },
          {
            "x": -1,
            "y": -0.7,
          },
          {
            "x": 0.5,
            "y": -0.7,
          },
        ],
        "stroke_width": 0.1,
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_silkscreen_path",
      },
      {
        "anchor_alignment": "center",
        "anchor_position": {
          "x": 0,
          "y": 1.2,
        },
        "ccw_rotation": 0,
        "font": "tscircuit2024",
        "font_size": 0.4,
        "layer": "top",
        "pcb_component_id": "pcb_component_0",
        "pcb_group_id": "pcb_group_0",
        "pcb_silkscreen_text_id": "pcb_silkscreen_text_0",
        "subcircuit_id": "subcircuit_source_group_2",
        "text": "R1",
        "type": "pcb_silkscreen_text",
      },
      {
        "height": 0.6,
        "layer": "top",
        "pcb_component_id": "pcb_component_1",
        "pcb_group_id": "pcb_group_0",
        "pcb_port_id": "pcb_port_2",
        "pcb_smtpad_id": "pcb_smtpad_2",
        "port_hints": [
          "1",
          "left",
        ],
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_smtpad",
        "width": 0.6,
        "x": -0.5,
        "y": 0,
      },
      {
        "height": 0.42,
        "layer": "top",
        "pcb_component_id": "pcb_component_1",
        "pcb_group_id": "pcb_group_0",
        "pcb_smtpad_id": "pcb_smtpad_2",
        "pcb_solder_paste_id": "pcb_solder_paste_2",
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_solder_paste",
        "width": 0.42,
        "x": -0.5,
        "y": 0,
      },
      {
        "height": 0.6,
        "layer": "top",
        "pcb_component_id": "pcb_component_1",
        "pcb_group_id": "pcb_group_0",
        "pcb_port_id": "pcb_port_3",
        "pcb_smtpad_id": "pcb_smtpad_3",
        "port_hints": [
          "2",
          "right",
        ],
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_smtpad",
        "width": 0.6,
        "x": 0.5,
        "y": 0,
      },
      {
        "height": 0.42,
        "layer": "top",
        "pcb_component_id": "pcb_component_1",
        "pcb_group_id": "pcb_group_0",
        "pcb_smtpad_id": "pcb_smtpad_3",
        "pcb_solder_paste_id": "pcb_solder_paste_3",
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_solder_paste",
        "width": 0.42,
        "x": 0.5,
        "y": 0,
      },
      {
        "layer": "top",
        "pcb_component_id": "pcb_component_1",
        "pcb_group_id": "pcb_group_0",
        "pcb_silkscreen_path_id": "pcb_silkscreen_path_1",
        "route": [
          {
            "x": 0.5,
            "y": 0.7,
          },
          {
            "x": -1,
            "y": 0.7,
          },
          {
            "x": -1,
            "y": -0.7,
          },
          {
            "x": 0.5,
            "y": -0.7,
          },
        ],
        "stroke_width": 0.1,
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_silkscreen_path",
      },
      {
        "anchor_alignment": "center",
        "anchor_position": {
          "x": 0,
          "y": 1.2,
        },
        "ccw_rotation": 0,
        "font": "tscircuit2024",
        "font_size": 0.4,
        "layer": "top",
        "pcb_component_id": "pcb_component_1",
        "pcb_group_id": "pcb_group_0",
        "pcb_silkscreen_text_id": "pcb_silkscreen_text_1",
        "subcircuit_id": "subcircuit_source_group_2",
        "text": "C1",
        "type": "pcb_silkscreen_text",
      },
      {
        "height": 1,
        "layer": "top",
        "pcb_component_id": "pcb_component_2",
        "pcb_group_id": "pcb_group_1",
        "pcb_port_id": "pcb_port_4",
        "pcb_smtpad_id": "pcb_smtpad_4",
        "port_hints": [
          "1",
          "left",
        ],
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_smtpad",
        "width": 1.1,
        "x": -0.85,
        "y": 0,
      },
      {
        "height": 0.7,
        "layer": "top",
        "pcb_component_id": "pcb_component_2",
        "pcb_group_id": "pcb_group_1",
        "pcb_smtpad_id": "pcb_smtpad_4",
        "pcb_solder_paste_id": "pcb_solder_paste_4",
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_solder_paste",
        "width": 0.77,
        "x": -0.85,
        "y": 0,
      },
      {
        "height": 1,
        "layer": "top",
        "pcb_component_id": "pcb_component_2",
        "pcb_group_id": "pcb_group_1",
        "pcb_port_id": "pcb_port_5",
        "pcb_smtpad_id": "pcb_smtpad_5",
        "port_hints": [
          "2",
          "right",
        ],
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_smtpad",
        "width": 1.1,
        "x": 0.85,
        "y": 0,
      },
      {
        "height": 0.7,
        "layer": "top",
        "pcb_component_id": "pcb_component_2",
        "pcb_group_id": "pcb_group_1",
        "pcb_smtpad_id": "pcb_smtpad_5",
        "pcb_solder_paste_id": "pcb_solder_paste_5",
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_solder_paste",
        "width": 0.77,
        "x": 0.85,
        "y": 0,
      },
      {
        "layer": "top",
        "pcb_component_id": "pcb_component_2",
        "pcb_group_id": "pcb_group_1",
        "pcb_silkscreen_path_id": "pcb_silkscreen_path_2",
        "route": [
          {
            "x": 0.85,
            "y": 0.9,
          },
          {
            "x": -1.5999999999999999,
            "y": 0.9,
          },
          {
            "x": -1.5999999999999999,
            "y": -0.9,
          },
          {
            "x": 0.85,
            "y": -0.9,
          },
        ],
        "stroke_width": 0.1,
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_silkscreen_path",
      },
      {
        "anchor_alignment": "center",
        "anchor_position": {
          "x": 0,
          "y": 1.4,
        },
        "ccw_rotation": 0,
        "font": "tscircuit2024",
        "font_size": 0.4,
        "layer": "top",
        "pcb_component_id": "pcb_component_2",
        "pcb_group_id": "pcb_group_1",
        "pcb_silkscreen_text_id": "pcb_silkscreen_text_2",
        "subcircuit_id": "subcircuit_source_group_2",
        "text": "R2",
        "type": "pcb_silkscreen_text",
      },
      {
        "height": 1.2,
        "layer": "top",
        "pcb_component_id": "pcb_component_3",
        "pcb_group_id": undefined,
        "pcb_port_id": "pcb_port_6",
        "pcb_smtpad_id": "pcb_smtpad_6",
        "port_hints": [
          "1",
          "left",
        ],
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_smtpad",
        "width": 0.85,
        "x": -1.075,
        "y": 0,
      },
      {
        "height": 0.84,
        "layer": "top",
        "pcb_component_id": "pcb_component_3",
        "pcb_group_id": undefined,
        "pcb_smtpad_id": "pcb_smtpad_6",
        "pcb_solder_paste_id": "pcb_solder_paste_6",
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_solder_paste",
        "width": 0.595,
        "x": -1.075,
        "y": 0,
      },
      {
        "height": 1.2,
        "layer": "top",
        "pcb_component_id": "pcb_component_3",
        "pcb_group_id": undefined,
        "pcb_port_id": "pcb_port_7",
        "pcb_smtpad_id": "pcb_smtpad_7",
        "port_hints": [
          "2",
          "right",
        ],
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_smtpad",
        "width": 0.85,
        "x": 1.075,
        "y": 0,
      },
      {
        "height": 0.84,
        "layer": "top",
        "pcb_component_id": "pcb_component_3",
        "pcb_group_id": undefined,
        "pcb_smtpad_id": "pcb_smtpad_7",
        "pcb_solder_paste_id": "pcb_solder_paste_7",
        "shape": "rect",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_solder_paste",
        "width": 0.595,
        "x": 1.075,
        "y": 0,
      },
      {
        "layer": "top",
        "pcb_component_id": "pcb_component_3",
        "pcb_group_id": undefined,
        "pcb_silkscreen_path_id": "pcb_silkscreen_path_3",
        "route": [
          {
            "x": 1.075,
            "y": 1,
          },
          {
            "x": -1.7,
            "y": 1,
          },
          {
            "x": -1.7,
            "y": -1,
          },
          {
            "x": 1.075,
            "y": -1,
          },
        ],
        "stroke_width": 0.1,
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_silkscreen_path",
      },
      {
        "anchor_alignment": "center",
        "anchor_position": {
          "x": 0,
          "y": 1.5,
        },
        "ccw_rotation": 0,
        "font": "tscircuit2024",
        "font_size": 0.4,
        "layer": "top",
        "pcb_component_id": "pcb_component_3",
        "pcb_group_id": undefined,
        "pcb_silkscreen_text_id": "pcb_silkscreen_text_3",
        "subcircuit_id": "subcircuit_source_group_2",
        "text": "R3",
        "type": "pcb_silkscreen_text",
      },
      {
        "layers": [
          "top",
        ],
        "pcb_component_id": "pcb_component_0",
        "pcb_group_id": "pcb_group_0",
        "pcb_port_id": "pcb_port_0",
        "source_port_id": "source_port_0",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_port",
        "x": -0.5,
        "y": 0,
      },
      {
        "layers": [
          "top",
        ],
        "pcb_component_id": "pcb_component_0",
        "pcb_group_id": "pcb_group_0",
        "pcb_port_id": "pcb_port_1",
        "source_port_id": "source_port_1",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_port",
        "x": 0.5,
        "y": 0,
      },
      {
        "layers": [
          "top",
        ],
        "pcb_component_id": "pcb_component_1",
        "pcb_group_id": "pcb_group_0",
        "pcb_port_id": "pcb_port_2",
        "source_port_id": "source_port_2",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_port",
        "x": -0.5,
        "y": 0,
      },
      {
        "layers": [
          "top",
        ],
        "pcb_component_id": "pcb_component_1",
        "pcb_group_id": "pcb_group_0",
        "pcb_port_id": "pcb_port_3",
        "source_port_id": "source_port_3",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_port",
        "x": 0.5,
        "y": 0,
      },
      {
        "layers": [
          "top",
        ],
        "pcb_component_id": "pcb_component_2",
        "pcb_group_id": "pcb_group_1",
        "pcb_port_id": "pcb_port_4",
        "source_port_id": "source_port_4",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_port",
        "x": -0.85,
        "y": 0,
      },
      {
        "layers": [
          "top",
        ],
        "pcb_component_id": "pcb_component_2",
        "pcb_group_id": "pcb_group_1",
        "pcb_port_id": "pcb_port_5",
        "source_port_id": "source_port_5",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_port",
        "x": 0.85,
        "y": 0,
      },
      {
        "layers": [
          "top",
        ],
        "pcb_component_id": "pcb_component_3",
        "pcb_group_id": undefined,
        "pcb_port_id": "pcb_port_6",
        "source_port_id": "source_port_6",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_port",
        "x": -1.075,
        "y": 0,
      },
      {
        "layers": [
          "top",
        ],
        "pcb_component_id": "pcb_component_3",
        "pcb_group_id": undefined,
        "pcb_port_id": "pcb_port_7",
        "source_port_id": "source_port_7",
        "subcircuit_id": "subcircuit_source_group_2",
        "type": "pcb_port",
        "x": 1.075,
        "y": 0,
      },
      {
        "cad_component_id": "cad_component_0",
        "footprinter_string": "0402",
        "model_jscad": undefined,
        "model_obj_url": undefined,
        "model_stl_url": undefined,
        "pcb_component_id": "pcb_component_0",
        "position": {
          "x": 0,
          "y": 0,
          "z": 0.7,
        },
        "rotation": {
          "x": 0,
          "y": 0,
          "z": 0,
        },
        "source_component_id": "source_component_0",
        "type": "cad_component",
      },
      {
        "cad_component_id": "cad_component_1",
        "footprinter_string": "0402",
        "model_jscad": undefined,
        "model_obj_url": undefined,
        "model_stl_url": undefined,
        "pcb_component_id": "pcb_component_1",
        "position": {
          "x": 0,
          "y": 0,
          "z": 0.7,
        },
        "rotation": {
          "x": 0,
          "y": 0,
          "z": 0,
        },
        "source_component_id": "source_component_1",
        "type": "cad_component",
      },
      {
        "cad_component_id": "cad_component_2",
        "footprinter_string": "0603",
        "model_jscad": undefined,
        "model_obj_url": undefined,
        "model_stl_url": undefined,
        "pcb_component_id": "pcb_component_2",
        "position": {
          "x": 0,
          "y": 0,
          "z": 0.7,
        },
        "rotation": {
          "x": 0,
          "y": 0,
          "z": 0,
        },
        "source_component_id": "source_component_2",
        "type": "cad_component",
      },
      {
        "cad_component_id": "cad_component_3",
        "footprinter_string": "0805",
        "model_jscad": undefined,
        "model_obj_url": undefined,
        "model_stl_url": undefined,
        "pcb_component_id": "pcb_component_3",
        "position": {
          "x": 0,
          "y": 0,
          "z": 0.7,
        },
        "rotation": {
          "x": 0,
          "y": 0,
          "z": 0,
        },
        "source_component_id": "source_component_3",
        "type": "cad_component",
      },
    ]
  `)
  const packOutput = convertCircuitJsonToPackOutput(circuitJson)

  expect(packOutput).toMatchInlineSnapshot(`
    {
      "components": [
        {
          "ccwRotationOffset": 0,
          "center": {
            "x": 0,
            "y": 0,
          },
          "componentId": "pcb_component_0",
          "pads": [
            {
              "absoluteCenter": {
                "x": -0.5,
                "y": 0,
              },
              "networkId": "unnamed0",
              "offset": {
                "x": -0.5,
                "y": 0,
              },
              "padId": "pcb_smtpad_0",
              "size": {
                "x": 0.6,
                "y": 0.6,
              },
              "type": "rect",
            },
            {
              "absoluteCenter": {
                "x": 0.5,
                "y": 0,
              },
              "networkId": "unnamed1",
              "offset": {
                "x": 0.5,
                "y": 0,
              },
              "padId": "pcb_smtpad_1",
              "size": {
                "x": 0.6,
                "y": 0.6,
              },
              "type": "rect",
            },
          ],
        },
        {
          "ccwRotationOffset": 0,
          "center": {
            "x": 0,
            "y": 0,
          },
          "componentId": "pcb_component_1",
          "pads": [
            {
              "absoluteCenter": {
                "x": -0.5,
                "y": 0,
              },
              "networkId": "unnamed2",
              "offset": {
                "x": -0.5,
                "y": 0,
              },
              "padId": "pcb_smtpad_2",
              "size": {
                "x": 0.6,
                "y": 0.6,
              },
              "type": "rect",
            },
            {
              "absoluteCenter": {
                "x": 0.5,
                "y": 0,
              },
              "networkId": "unnamed3",
              "offset": {
                "x": 0.5,
                "y": 0,
              },
              "padId": "pcb_smtpad_3",
              "size": {
                "x": 0.6,
                "y": 0.6,
              },
              "type": "rect",
            },
          ],
        },
        {
          "ccwRotationOffset": 0,
          "center": {
            "x": 0,
            "y": 0,
          },
          "componentId": "pcb_component_2",
          "pads": [
            {
              "absoluteCenter": {
                "x": -0.85,
                "y": 0,
              },
              "networkId": "unnamed4",
              "offset": {
                "x": -0.85,
                "y": 0,
              },
              "padId": "pcb_smtpad_4",
              "size": {
                "x": 1.1,
                "y": 1,
              },
              "type": "rect",
            },
            {
              "absoluteCenter": {
                "x": 0.85,
                "y": 0,
              },
              "networkId": "unnamed5",
              "offset": {
                "x": 0.85,
                "y": 0,
              },
              "padId": "pcb_smtpad_5",
              "size": {
                "x": 1.1,
                "y": 1,
              },
              "type": "rect",
            },
          ],
        },
        {
          "ccwRotationOffset": 0,
          "center": {
            "x": 0,
            "y": 0,
          },
          "componentId": "pcb_component_3",
          "pads": [
            {
              "absoluteCenter": {
                "x": -1.075,
                "y": 0,
              },
              "networkId": "unnamed6",
              "offset": {
                "x": -1.075,
                "y": 0,
              },
              "padId": "pcb_smtpad_6",
              "size": {
                "x": 0.85,
                "y": 1.2,
              },
              "type": "rect",
            },
            {
              "absoluteCenter": {
                "x": 1.075,
                "y": 0,
              },
              "networkId": "unnamed7",
              "offset": {
                "x": 1.075,
                "y": 0,
              },
              "padId": "pcb_smtpad_7",
              "size": {
                "x": 0.85,
                "y": 1.2,
              },
              "type": "rect",
            },
          ],
        },
      ],
      "minGap": 0,
      "packOrderStrategy": "largest_to_smallest",
      "packPlacementStrategy": "shortest_connection_along_outline",
    }
  `)

  const graphics = getGraphicsFromPackOutput(packOutput)

  expect(
    getSvgFromGraphicsObject(graphics, {
      backgroundColor: "white",
    }),
  ).toMatchSvgSnapshot(import.meta.path)
})
